# Generated by Django 5.1.2 on 2025-01-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(default='sample.jpg', upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_picture', models.ImageField(upload_to='picture')),
                ('item_price', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=6)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_App.category')),
            ],
        ),
    ]
