# Generated by Django 5.1.2 on 2025-02-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_App', '0002_alter_item_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.CharField(max_length=100),
        ),
    ]
