# Generated by Django 5.1.2 on 2025-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0005_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
