# Generated by Django 5.1.2 on 2025-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_buynow_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White')], default='Black', max_length=20),
        ),
        migrations.AddField(
            model_name='buynow',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=10),
        ),
    ]
