# Generated by Django 5.1.2 on 2025-02-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0007_buynow_color_buynow_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buynow',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
